version: '2'

services:
  cassandra:
    image: cassandra
    restart: always
    volumes:
      - cassandradata:/var/lib/cassandra
    ports:
      - 7199:7199
    expose:
      - 9160
    environment:
      - CASSANDRA_START_RPC=true

  kairosdb:
    image: stakater/kairosdb
    restart: always
    links:
      - cassandra
    volumes:
      - kairoslog:/opt/kairosdb/log
      - kairosdata:/data
    ports:
      - 8080:8080
    expose:
      - 4242
    environment:
      - CASS_HOSTS=cassandra:9160
      - REPFACTOR=1
      - PORT_TELNET=4242
      - PORT_HTTP=8080

  grafana:
    image: grafana/grafana:2.6.0
    restart: always
    ports:
      - 3000:3000
    volumes:
      - grafanadata:/var/lib/grafana

volumes:
 grafanadata:
 cassandradata:
 kairosdata:
 kairoslog:
 